"""added profile pic

Revision ID: 328d35e7f389
Revises: 5bea4652b9da
Create Date: 2022-01-14 21:32:46.513107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328d35e7f389'
down_revision = '5bea4652b9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
