"""added password field

Revision ID: 727d28de66bb
Revises: be66d8b9ba55
Create Date: 2021-05-17 16:04:07.155257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727d28de66bb'
down_revision = 'be66d8b9ba55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
