"""added Foreign Key one to many user to posts

Revision ID: 9fa07be75366
Revises: da5aaca052c8
Create Date: 2021-09-24 19:45:56.270124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fa07be75366'
down_revision = 'da5aaca052c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
